spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Default/Common configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# JWT Configuration (common)
jwt:
  expiration: 86400000 # 24 hours in milliseconds

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/lifegoalsapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"

jwt:
  secret: your-256-bit-secret-key-here-make-it-long-and-secure

logging:
  level:
    org.springframework.security: DEBUG
    com.example.lifegoalsapp: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    com.example.lifegoalsapp: INFO 